ktor:
  application:
    modules:
      - dev.praja.porgs.ApplicationKt.bootstrap
  deployment:
    port: 8080

app:
  name: "Praja Organizations"
  shortName: "PORGS"
  version: "0.0.1"
  db:
    readPoolSize: 10
    busyTimeout: 5000
