package main

// TODO: Main should combine translations from each plugin.
// TODO: L1NAME, ... should be a site-wide configuration
var text = map[string]map[string]string{
	"en": {
		"L1NAME":               "Province",
		"L2NAME":               "District",
		"L3NAME":               "District Secretariat Division",
		"L4NAME":               "Grama Niladhari Division",
		"core":                 "People and Organizations",
		"task":                 "Work & Responsibilities",
		"site-title":           "Sri Lanka",
		"menu_home":            "home",
		"menu_login":           "login",
		"menu_logout":          "logout",
		"link_back":            "back",
		"root_welcome":         "Welcome.",
		"login_login":          "Login",
		"login_username":       "Username",
		"login_password":       "Password",
		"home_logged_in_as":    "Logged-in as",
		"org_no_sub_orgs":      "This organization has no sub-organizations.",
		"List organizations":   "List organizations",
		"Create person record": "Create person record",
	},
	"si": {
		"L1NAME":               "පළාත",
		"L2NAME":               "දිස්ත්‍රික්කය",
		"L3NAME":               "ප්‍රාදේශීය ලේකම් කොට්ඨාසය",
		"L4NAME":               "ග්‍රාම නිලධාරී කොට්ඨාශය",
		"core":                 "පුද්ගලයන් සහ සංවිධාන",
		"task":                 "වගකීම් සහ වැඩ",
		"site-title":           "ශ්‍රී ලංකාව",
		"menu_home":            "මුල් පිටුව",
		"menu_login":           "ඇතුල් වන්න",
		"menu_logout":          "ඉවත් වන්න",
		"link_back":            "ආපසු",
		"root_welcome":         "ආයුබෝවන්.",
		"login_login":          "ඇතුල් වන්න",
		"login_username":       "පරිශීලක නාමය",
		"login_password":       "මුරපදය",
		"home_logged_in_as":    "පරිශීලක නාමය",
		"org_no_sub_orgs":      "මෙම සංවිධානයේ උප සංවිධාන නැත.",
		"List organizations":   "ආයතන ලැයිස්තුව",
		"Create person record": "අළුත් පුද්ගල රෙකෝඩයක් සාදන්න",
	},
	"ta": {
		"L1NAME":               "மாகாணம்",
		"L2NAME":               "மாவட்டம்",
		"L3NAME":               "மாவட்டச் செயலகப் பிரிவு",
		"L4NAME":               "கிராம அலுவலர் பிரிவு",
		"core":                 "மக்கள் மற்றும் அமைப்புகள்",
		"task":                 "வேலை & பொறுப்புகள்",
		"site-title":           "இலங்கை",
		"menu_home":            "முகப்பு",
		"menu_login":           "உள்நுழை",
		"menu_logout":          "வெளியேறு",
		"link_back":            "பின்னால்",
		"root_welcome":         "வரவேற்கின்றேன்.",
		"login_login":          "உள்நுழை",
		"login_username":       "பயனர் பெயர்",
		"login_password":       "கடவுச்சொல்",
		"home_logged_in_as":    "பயனர் பெயர்",
		"org_no_sub_orgs":      "இந்த அமைப்புக்கு துணை அமைப்புகள் இல்லை.",
		"List organizations":   "அமைப்புகளை பட்டியலிடு",
		"Create person record": "புதிய நபர் பதிவை உருவாக்கவும்",
	},
}
